on:
  workflow_call:
    inputs:
      pr_id:
        required: true
        type: string
      owner:
        type: string
      name:
        type: string
jobs:
  check_reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Get Reviews
        run: |
          reviews=$(gh api graphql -F owner=$owner -F name=$REPO -f query='
            query {
              organization(login: "FishyGeeksKingdom") {
                repository(name: "wy-water") {
                  id
                  name
                  pullRequest(number: 1) {
                    id
                    merged
                    mergeable
                    number
                    reviewDecision
                    assignees(first: 10) {
                      edges {
                        node {
                          id
                          login
                        }
                      }
                    }
                    reviews(last: 10) {
                      edges {
                        node {
                          id
                          state
                          author {
                            ... on User {
                              id
                              email
                              login
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          ')

          echo 'PR_REVIEWS='$reviews >> $GITHUB_ENV

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Echo Reviews
        run: echo $PR_REVIEWS

  get_approval_team:
    runs-on: ubuntu-latest
    steps:
      - name: Get Team
        run: |
          team_members=$(gh api graphql -F owner=$owner -F name=$REPO -f query='
            query {
              organization(login: "FishyGeeksKingdom") {
                repository(name: "wy-water") {
                  id
                  name
                  pullRequest(number: 1) {
                    id
                    merged
                    mergeable
                    number
                    reviewDecision
                    assignees(first: 10) {
                      edges {
                        node {
                          id
                          login
                        }
                      }
                    }
                    reviews(last: 10) {
                      edges {
                        node {
                          id
                          state
                          author {
                            ... on User {
                              id
                              email
                              login
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          ')

          echo 'APP_TEAM='$team_members >> $GITHUB_ENV

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Echo Team
        run: echo $APP_TEAM
