on:
  workflow_call:
    secrets:
      team_key:
        required: true
    inputs:
      pr_id:
        required: true
        type: string
      owner:
        type: string
      name:
        type: string
jobs:
  check_reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Get Reviews
        run: |
          reviews=$(gh api graphql -F owner=$owner -F name=$REPO -f query='
            query {
              organization(login: "FishyGeeksKingdom") {
                repository(name: "wy-water") {
                  id
                  name
                  pullRequest(number: 1) {
                    id
                    merged
                    mergeable
                    number
                    reviewDecision
                    assignees(first: 10) {
                      edges {
                        node {
                          id
                          login
                        }
                      }
                    }
                    reviews(last: 10) {
                      edges {
                        node {
                          id
                          state
                          author {
                            ... on User {
                              id
                              email
                              login
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          ')

          echo 'PR_REVIEWS='$reviews >> $GITHUB_ENV

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Echo Reviews
        run: echo ${{ secrets.PR_REVIEWS }}
    steps:
      - name: Get Team
        run: |
          team_members=$(gh api graphql -F owner=$owner -F name=$REPO -f query='
            query {
              organization(login: "FishyGeeksKingdom") {
                teams(first: 10) {
                  edges {
                    node {
                      members(first: 10) {
                        edges {
                          node {
                            id
                            login
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          ')

          echo 'APP_TEAM='$team_members >> $GITHUB_ENV

        env:
          GITHUB_TOKEN: ${{ secrets.TEAM_KEY }}

      - name: Run Echo Team
        run: echo $APP_TEAM
    steps:
      - name: Run Echo Team
        run: |
          echo $APP_TEAM
          echo $PR_REVIEWS
      - uses: actions/checkout@v2
      - name: Python Script
        run: python checkReviews.py $PR_REVIEWS $APP_TEAM
        shell: sh

      - name: Run Echo Team
        run: echo $APP_TEAM
