on:
  workflow_call:
    inputs:
      pr_id:
        required: true
        type: string
jobs:
  check_reviews:
    runs-on: ubuntu-latest
    steps:
      - run: |
          reviews="$(gh api graphql -F owner=$owner -F name=$REPO -f query='
            query($name: String!, $owner: String!) {
              organization(login: "FishyGeeksKingdom") {
                repository(name: "wy-water") {
                  id
                  name
                  pullRequest(number: 1) {
                    id
                    merged
                    mergeable
                    number
                    reviewDecision
                    assignees(first: 10) {
                      edges {
                        node {
                          id
                          login
                        }
                      }
                    }
                    reviews(last: 10) {
                      edges {
                        node {
                          id
                          state
                          author {
                            ... on User {
                              id
                              email
                              login
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }' --jq '.data.repository.reviews')"
