name: Publish Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, closed]
    branches:
      - main
    paths:
      - ".github/**"
jobs:
  Builds:
    runs-on: ubuntu-latest
    steps:
      - run: echo Nothing To Build
