on:
  pull_request:
    types: [closed]
  publish:
  if: github.ref == 'refs/heads/main' && github.event.pull_request.merged == true
  needs: build
  runs-on: ubuntu-latest
  # Fresh checkout to protect from injection during the previous build step (like prepack)
  jobs:
    check_review:
      uses: ./.github/workflows/checkReviewers.yml
      with:
        pr_id: ${{ github.event.pull_request.number }}
    checkout_and_publish:
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 14
        - name: Publish
          # VERY IMPORTANT NOT TO RUN SCRIPTS TO PROTECT FROM MALICIOUS PACKAGES
          run: |
            echo Maybe Success!
