on:
  pull_request:
    branches:
      - main
jobs:
  # This workflow contains a single job called "build"
  check-version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - name: Run a multi-line script Target
        run: |
          echo ${{ github.workspace }}
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}

          var=$(cat package.json)
          echo $var

          versionText=$(cat package.json | jq -r '.version') 
          echo $versionText

          versionNumber=$(echo $versionText | sed 's/.//g')
          echo $versionNumber

      - uses: actions/checkout@v2
      - name: Run a multi-line script Source
        run: |
          echo ${{ github.head_ref }}
          var=$(cat package.json)
          echo $var
